language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /v(\d+)\.(\d+)\.(\d+)/
matrix:
  allow_failures:
  - julia: nightly
after_success:
  - julia -e 'using Pkg; import GlobalSensitivityAnalysis.jl; cd(dirname(pathof(GlobalSensitivityAnalysis))); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; import GlobalSensitivityAnalysis.jl; cd(dirname(pathof(GlobalSensitivityAnalysis))); using Coverage; Coveralls.submit(process_folder())'

